import { useEffect, useState } from 'react';
import TodoListItem from './TodoListItem';
import {Box, Button, Grid, List, Stack, TextField, Typography} from "@mui/material";
import { mockTodos } from "../mock/todos";

export default function TodoList() {
  const [todos, setTodos] = useState([]);
  const [newTask, setNewTask] = useState('');

  useEffect(() => {
    // load mock data
    setTodos(mockTodos);
  }, []);

  const handleChange = (event) => {
    setNewTask(event.target.value);
  }

  const handleKeyDown = (event) => {
    if (event.keyCode === 13) addTodo();
  }

  const addTodo = () => {
    if (newTask.trim() !== '') {
      const newData =   {
        "task": newTask,
        "completed": false
      }
      setTodos([...todos, newData]);
    }
    // following: call api to store new task
    // userId should be current user id
    // id will be auto-generated by server
  }

  return (
    <Stack spacing={2}>
      <Grid container spacing={2}>
        <Grid item xs={12}>
          <Box sx={{bgcolor: '#fefae0', borderRadius: '10px', minHeight: 70, maxHeight: 412, overflowY: 'auto'}}>
            { todos.length > 0 ? (
              <List sx={{ width: '100%'}}>
                {todos.map((item, index) => (
                  <TodoListItem key={index} todos={item}/>
                ))}
              </List>
            ) : <Typography p={3} color="#bc6c25">No Tasks</Typography>}
          </Box>
        </Grid>
        <Grid item xs={12} sm={10}>
          <TextField id="task" variant="standard" label="New Task" onChange={handleChange} onKeyDown={handleKeyDown}
                     sx={{width: '100%'}}/>
        </Grid>
        <Grid item xs={12} sm={2}>
          <Button variant="contained" onClick={addTodo} sx={{bgcolor: '#283618', width: '100%'}}>ADD</Button>
        </Grid>
      </Grid>
    </Stack>
  )
}